version: '3.8'

services:
  app:
    build:
      context: .              # Titik ini artinya folder 'laravel-docker-new'
      dockerfile: Dockerfile  # Dockerfile ada di sini
    container_name: laravel_app
    restart: always
    working_dir: /var/www
    volumes:
      - ./belajarDocker:/var/www  # SINKRONKAN folder Laravel ke dalam container
    networks:
      - laravel

  web:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - ./belajarDocker:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge