server {
    listen 80;
    # Sesuaikan root ke folder public di dalam container
    root /var/www/public; 
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        # 'app' adalah nama service di docker-compose.yml
        fastcgi_pass app:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}